### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ueman**
- Fix missing translation warnings related to the in app purchase
- fix two async warnings
- show BottomAppBar on TransactionList

### CODE REVIEW

**Comment by NPadrutt** [comment]
Hi
that the BottomAppBar  is only in the minimal mode in the transactionlist was with purpose, since I thought that there won't be default place where you wanna add new transactions. Do you think it's better to show it in normal size?

**Comment by ueman** [comment]
Honestly I think it just looks better if the BottomAppBar is expanded. Also I think it doesn't really bother the user as the option to add a new transaction is now a click less away.

**Comment by NPadrutt** [comment]
My thought was more about the space on smaller devices with low resolution. But lets see how it works out =)

**Comment by ueman** [comment]
I have a Nokia Lumia 530 as a test device (it has a 4 inch display) and it doesn't take away that much space. You can still fit eight transactions on that page.

**Comment by NPadrutt** [comment]
that sounds not bad. I will have a loot at it on my phone.

**Comment by ueman** [comment]
I've made a screenshot: http://i.imgur.com/OoIADPJ.jpg

**Comment by NPadrutt** [comment]
That looks nice. Btw, I made some changes to the design. Would be great to get some feedback (see issue Fine tuning design #292).

**Pull request merged**
